# Generated by Django 5.1.7 on 2025-03-28 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdocumenthistory',
            options={'ordering': ['-accessed_at'], 'verbose_name': 'Document History', 'verbose_name_plural': 'Document Histories'},
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdfprocessor.documentcategory'),
        ),
    ]
